# Generated by Django 5.2 on 2025-04-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_api', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
