# Generated by Django 5.2 on 2025-04-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_api', '0003_drink_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
